### ISSUE TITLE
Lot of test broken, any plan to fix that ?

### ISSUE THREAD

**Issue by MoOx** [unindented/jscs-loader#5]
Current travis status report that a lot of tests are not passing.
fmc, I'm having some issue that are not reported by this loader, but reported by jscs directly.
Do you need some help or just some time ?

**Comment by unindented** [comment]
Fixed it right now, and bumped to version `0.0.5` with the fix. See this discussion for the root cause: https://github.com/spenceralger/rcloader/issues/5

You may see `jshint-loader` misbehaving as well, because of the same thing. I've opened a pull request there: https://github.com/webpack/jshint-loader/pull/14.

Voice your concerns in both discussions too, please.

**Comment by MoOx** [comment]
I will. Thanks for the quick reply!
