### ISSUE TITLE
Add support for esnext option

### ISSUE THREAD

**Issue by jaredhughes** [unindented/jscs-loader#6]
The option `esnext: true` does not seem to be recognized by this loader, returning warnings for "unexpected reserved words" in both `.js` and `.jsx` files. Manually running jscs with the `--esnext` flag, however, returns no errors.

I'm passing the option in webpack.config.js:
```
jscs: {
  esnext: true
},
```
as well as in my local and global .jscsrc files.

This appears to be an update Grunt, Gulp, and other task runners have had to add support for, so it's probably a similar issue for this loader:
https://github.com/jscs-dev/grunt-jscs/issues/62

**Comment by unindented** [comment]
I've pushed some changes so that tests run with the `esnext` option (https://github.com/unindented/jscs-loader/commit/cd85a4a0749c1ad4eeef89d931308863b485702c) and they seem to be passing (https://travis-ci.org/unindented/jscs-loader).

I've also tried adding `esnext` to one of my projects, and things work fine.

Can you create a small example (maybe fork the repo and edit https://github.com/unindented/jscs-loader/tree/master/example) to demonstrate your issue?

PD: I think the problem in `grunt-jscs` is unrelated. They were manually deleting the option from the hash, but I'm not doing such a thing.

**Comment by jaredhughes** [comment]
Thanks for the prompt response and taking the time to look into it. It seems to be working properly now, although I'm not entirely clear as to what fixed it.

**Comment by unindented** [comment]
:+1:
